/**
 * Sector taxonomy and the fundamental "bands" each sector's companies are drawn
 * from. Bands encode how Indian listed sectors actually differ: FMCG trades at
 * high multiples with high ROE and little debt; PSU-heavy energy at low
 * multiples with high payouts; lenders have no meaningful operating margin or
 * debt/equity. Values are plausible ranges, not a dataset.
 */

export type Band = readonly [number, number];

export interface SectorProfile {
  name: string;
  /** Relative share of listed companies. */
  weight: number;
  industries: readonly string[];
  /** Multiplier on size-based volatility. */
  volatility: number;
  /** Loading on the market factor. */
  beta: Band;
  pe: Band;
  roe: Band;
  revenueGrowth: Band;
  /** Operating margin band; `null` for lenders. */
  operatingMargin: Band | null;
  netMargin: Band;
  /** Debt/equity band; `null` where leverage is not meaningful. */
  debtToEquity: Band | null;
  dividendYield: Band;
  /** Base probability that a small company is loss-making. */
  lossRate: number;
  /** Words used to name synthetic companies in this sector. */
  nameParts: readonly string[];
}

export const SECTORS: readonly SectorProfile[] = [
  {
    name: 'Banking',
    weight: 2.2,
    industries: ['Private Banks', 'Public Sector Banks', 'Small Finance Banks'],
    volatility: 1.0,
    beta: [0.9, 1.35],
    pe: [7, 22],
    roe: [8, 18],
    revenueGrowth: [8, 22],
    operatingMargin: null,
    netMargin: [12, 28],
    debtToEquity: null,
    dividendYield: [0.4, 3.2],
    lossRate: 0.06,
    nameParts: ['Bank', 'Co-operative Bank', 'Finance Bank', 'Commercial Bank'],
  },
  {
    name: 'Financial Services',
    weight: 9,
    industries: [
      'NBFC',
      'Housing Finance',
      'Asset Management',
      'Capital Markets',
      'Microfinance',
      'Fintech',
    ],
    volatility: 1.12,
    beta: [0.95, 1.45],
    pe: [10, 38],
    roe: [9, 24],
    revenueGrowth: [10, 34],
    operatingMargin: null,
    netMargin: [10, 32],
    debtToEquity: [1.2, 4.8],
    dividendYield: [0.2, 2.2],
    lossRate: 0.12,
    nameParts: ['Capital', 'Finserv', 'Credit', 'Finance', 'Holdings', 'Investments', 'Securities'],
  },
  {
    name: 'Insurance',
    weight: 0.8,
    industries: ['Life Insurance', 'General Insurance', 'Insurance Broking'],
    volatility: 0.85,
    beta: [0.7, 1.05],
    pe: [22, 75],
    roe: [8, 20],
    revenueGrowth: [8, 24],
    operatingMargin: null,
    netMargin: [3, 12],
    debtToEquity: null,
    dividendYield: [0.1, 1.4],
    lossRate: 0.08,
    nameParts: ['Assurance', 'Insurance', 'Life Insurance', 'General Insurance'],
  },
  {
    name: 'Information Technology',
    weight: 7,
    industries: [
      'IT Services',
      'Software Products',
      'Engineering R&D',
      'IT Consulting',
      'BPM & ITeS',
      'Data & AI',
    ],
    volatility: 0.95,
    beta: [0.6, 1.05],
    pe: [17, 45],
    roe: [14, 38],
    revenueGrowth: [3, 22],
    operatingMargin: [14, 28],
    netMargin: [9, 22],
    debtToEquity: [0, 0.18],
    dividendYield: [0.4, 3.6],
    lossRate: 0.1,
    nameParts: [
      'Infotech',
      'Softech',
      'Systems',
      'Technologies',
      'Digital',
      'Datacore',
      'Infosystems',
    ],
  },
  {
    name: 'Pharmaceuticals',
    weight: 6,
    industries: ['Formulations', 'API & Intermediates', 'CDMO', 'Biologics', 'Generics'],
    volatility: 0.92,
    beta: [0.55, 0.95],
    pe: [18, 46],
    roe: [9, 26],
    revenueGrowth: [5, 21],
    operatingMargin: [14, 30],
    netMargin: [8, 22],
    debtToEquity: [0, 0.55],
    dividendYield: [0.2, 1.8],
    lossRate: 0.1,
    nameParts: ['Pharma', 'Labs', 'Lifesciences', 'Remedies', 'Biotech', 'Healthcare', 'Drugs'],
  },
  {
    name: 'Healthcare Services',
    weight: 1.8,
    industries: ['Hospitals', 'Diagnostics', 'Medical Devices', 'Health-tech'],
    volatility: 0.95,
    beta: [0.6, 1.0],
    pe: [32, 85],
    roe: [8, 20],
    revenueGrowth: [10, 30],
    operatingMargin: [14, 28],
    netMargin: [6, 16],
    debtToEquity: [0.1, 0.9],
    dividendYield: [0, 0.9],
    lossRate: 0.16,
    nameParts: ['Hospitals', 'Medicare', 'Diagnostics', 'Health', 'Medisystems'],
  },
  {
    name: 'Automobile',
    weight: 5,
    industries: [
      'Passenger Vehicles',
      'Two Wheelers',
      'Commercial Vehicles',
      'Auto Components',
      'Tyres',
      'Batteries & EV',
    ],
    volatility: 1.08,
    beta: [0.85, 1.3],
    pe: [14, 38],
    roe: [9, 26],
    revenueGrowth: [4, 24],
    operatingMargin: [8, 20],
    netMargin: [4, 12],
    debtToEquity: [0.05, 1.0],
    dividendYield: [0.4, 2.8],
    lossRate: 0.1,
    nameParts: ['Motors', 'Autotech', 'Auto Components', 'Mobility', 'Forgings', 'Drivelines'],
  },
  {
    name: 'FMCG',
    weight: 3.4,
    industries: ['Packaged Foods', 'Personal Care', 'Household Products', 'Beverages', 'Tobacco'],
    volatility: 0.72,
    beta: [0.45, 0.85],
    pe: [32, 72],
    roe: [16, 55],
    revenueGrowth: [4, 15],
    operatingMargin: [12, 26],
    netMargin: [8, 18],
    debtToEquity: [0, 0.3],
    dividendYield: [0.8, 3.6],
    lossRate: 0.08,
    nameParts: ['Consumer', 'Foods', 'Products', 'Brands', 'Nutrition', 'Agro Foods'],
  },
  {
    name: 'Consumer Durables',
    weight: 3,
    industries: [
      'Home Appliances',
      'Electronics Manufacturing',
      'Cables & Wires',
      'Consumer Electricals',
      'Jewellery & Watches',
    ],
    volatility: 1.02,
    beta: [0.8, 1.2],
    pe: [28, 70],
    roe: [12, 30],
    revenueGrowth: [6, 28],
    operatingMargin: [7, 16],
    netMargin: [4, 11],
    debtToEquity: [0.02, 0.6],
    dividendYield: [0.2, 1.6],
    lossRate: 0.1,
    nameParts: ['Appliances', 'Electronics', 'Cables', 'Electricals', 'Jewellers', 'Durables'],
  },
  {
    name: 'Retail & Consumer Services',
    weight: 3,
    industries: ['Retail', 'E-commerce', 'Hotels & Hospitality', 'QSR', 'Leisure'],
    volatility: 1.15,
    beta: [0.85, 1.3],
    pe: [40, 120],
    roe: [6, 24],
    revenueGrowth: [12, 38],
    operatingMargin: [6, 18],
    netMargin: [2, 10],
    debtToEquity: [0.1, 1.2],
    dividendYield: [0, 0.8],
    lossRate: 0.22,
    nameParts: ['Retail', 'Hotels', 'Hospitality', 'Stores', 'Lifestyle', 'Resorts'],
  },
  {
    name: 'Oil, Gas & Fuels',
    weight: 1.6,
    industries: [
      'Refining & Marketing',
      'Exploration & Production',
      'Gas Distribution',
      'Coal',
      'Lubricants',
    ],
    volatility: 1.0,
    beta: [0.8, 1.2],
    pe: [5, 18],
    roe: [8, 22],
    revenueGrowth: [-4, 14],
    operatingMargin: [6, 22],
    netMargin: [3, 14],
    debtToEquity: [0.15, 1.1],
    dividendYield: [2, 7.5],
    lossRate: 0.08,
    nameParts: ['Petro', 'Energy', 'Gas', 'Fuels', 'Petroleum', 'Lubricants'],
  },
  {
    name: 'Power',
    weight: 2.2,
    industries: ['Power Generation', 'Transmission', 'Renewable Energy', 'Power Distribution'],
    volatility: 1.08,
    beta: [0.85, 1.3],
    pe: [12, 38],
    roe: [8, 18],
    revenueGrowth: [4, 24],
    operatingMargin: [22, 45],
    netMargin: [8, 22],
    debtToEquity: [0.8, 2.6],
    dividendYield: [0.8, 4.2],
    lossRate: 0.1,
    nameParts: ['Power', 'Energy', 'Renewables', 'Green Energy', 'Transmission'],
  },
  {
    name: 'Metals & Mining',
    weight: 3,
    industries: ['Steel', 'Aluminium', 'Copper & Zinc', 'Mining', 'Ferro Alloys'],
    volatility: 1.38,
    beta: [1.05, 1.55],
    pe: [6, 22],
    roe: [6, 24],
    revenueGrowth: [-8, 26],
    operatingMargin: [10, 26],
    netMargin: [3, 14],
    debtToEquity: [0.2, 1.6],
    dividendYield: [0.8, 7],
    lossRate: 0.12,
    nameParts: ['Steel', 'Metals', 'Alloys', 'Minerals', 'Ispat', 'Castings'],
  },
  {
    name: 'Chemicals',
    weight: 6,
    industries: [
      'Specialty Chemicals',
      'Agrochemicals',
      'Fertilisers',
      'Petrochemicals',
      'Dyes & Pigments',
    ],
    volatility: 1.06,
    beta: [0.75, 1.15],
    pe: [14, 42],
    roe: [9, 26],
    revenueGrowth: [0, 24],
    operatingMargin: [10, 24],
    netMargin: [5, 15],
    debtToEquity: [0.05, 0.9],
    dividendYield: [0.3, 2.4],
    lossRate: 0.1,
    nameParts: ['Chemicals', 'Organics', 'Agrochem', 'Fertilisers', 'Polymers', 'Specialities'],
  },
  {
    name: 'Capital Goods',
    weight: 6,
    industries: [
      'Industrial Machinery',
      'Electrical Equipment',
      'Defence',
      'Railway Equipment',
      'Bearings & Components',
    ],
    volatility: 1.12,
    beta: [0.9, 1.35],
    pe: [22, 65],
    roe: [10, 26],
    revenueGrowth: [8, 30],
    operatingMargin: [9, 20],
    netMargin: [5, 14],
    debtToEquity: [0.02, 0.8],
    dividendYield: [0.2, 1.8],
    lossRate: 0.1,
    nameParts: [
      'Engineering',
      'Industries',
      'Electricals',
      'Machines',
      'Defence Systems',
      'Equipments',
    ],
  },
  {
    name: 'Construction & Infrastructure',
    weight: 4,
    industries: [
      'EPC & Construction',
      'Roads & Highways',
      'Ports & Airports',
      'Urban Infrastructure',
    ],
    volatility: 1.22,
    beta: [1.0, 1.45],
    pe: [10, 32],
    roe: [7, 20],
    revenueGrowth: [6, 30],
    operatingMargin: [9, 22],
    netMargin: [3, 11],
    debtToEquity: [0.4, 2.2],
    dividendYield: [0.1, 1.6],
    lossRate: 0.14,
    nameParts: ['Infra', 'Infraprojects', 'Constructions', 'Buildcon', 'Projects'],
  },
  {
    name: 'Cement & Building Materials',
    weight: 3,
    industries: ['Cement', 'Paints', 'Tiles & Sanitaryware', 'Plywood & Laminates', 'Pipes'],
    volatility: 1.0,
    beta: [0.8, 1.2],
    pe: [18, 48],
    roe: [8, 24],
    revenueGrowth: [3, 18],
    operatingMargin: [11, 24],
    netMargin: [5, 13],
    debtToEquity: [0.05, 0.9],
    dividendYield: [0.3, 2.2],
    lossRate: 0.1,
    nameParts: ['Cement', 'Paints', 'Ceramics', 'Laminates', 'Pipes', 'Buildmat'],
  },
  {
    name: 'Realty',
    weight: 2.6,
    industries: ['Residential', 'Commercial & REITs', 'Township Developers'],
    volatility: 1.42,
    beta: [1.1, 1.6],
    pe: [15, 60],
    roe: [4, 18],
    revenueGrowth: [-6, 36],
    operatingMargin: [15, 38],
    netMargin: [6, 24],
    debtToEquity: [0.2, 1.8],
    dividendYield: [0, 1.2],
    lossRate: 0.2,
    nameParts: ['Realty', 'Estates', 'Developers', 'Properties', 'Habitats'],
  },
  {
    name: 'Telecommunication',
    weight: 1,
    industries: ['Telecom Services', 'Telecom Infrastructure', 'Telecom Equipment'],
    volatility: 1.15,
    beta: [0.75, 1.2],
    pe: [18, 70],
    roe: [2, 22],
    revenueGrowth: [4, 22],
    operatingMargin: [18, 52],
    netMargin: [2, 16],
    debtToEquity: [0.6, 2.8],
    dividendYield: [0, 2.2],
    lossRate: 0.22,
    nameParts: ['Telecom', 'Communications', 'Networks', 'Telelinks'],
  },
  {
    name: 'Media & Entertainment',
    weight: 1.8,
    industries: ['Broadcasting', 'Film Production', 'Print Media', 'Digital Media', 'Gaming'],
    volatility: 1.25,
    beta: [0.8, 1.25],
    pe: [14, 55],
    roe: [3, 18],
    revenueGrowth: [-4, 26],
    operatingMargin: [8, 26],
    netMargin: [2, 14],
    debtToEquity: [0.05, 0.9],
    dividendYield: [0, 2],
    lossRate: 0.26,
    nameParts: ['Media', 'Broadcast', 'Entertainment', 'Studios', 'Films'],
  },
  {
    name: 'Textiles & Apparel',
    weight: 4,
    industries: [
      'Cotton Yarn',
      'Home Textiles',
      'Branded Apparel',
      'Synthetic Fibres',
      'Technical Textiles',
    ],
    volatility: 1.18,
    beta: [0.75, 1.15],
    pe: [10, 34],
    roe: [5, 20],
    revenueGrowth: [-6, 22],
    operatingMargin: [7, 17],
    netMargin: [2, 9],
    debtToEquity: [0.2, 1.4],
    dividendYield: [0.2, 2.6],
    lossRate: 0.16,
    nameParts: ['Textiles', 'Mills', 'Spinners', 'Fabrics', 'Apparel', 'Synthetics'],
  },
  {
    name: 'Logistics & Transport',
    weight: 2,
    industries: ['Logistics', 'Shipping', 'Airlines', 'Rail Freight', 'Warehousing'],
    volatility: 1.12,
    beta: [0.85, 1.3],
    pe: [16, 48],
    roe: [8, 24],
    revenueGrowth: [5, 26],
    operatingMargin: [8, 22],
    netMargin: [3, 12],
    debtToEquity: [0.1, 1.4],
    dividendYield: [0.2, 2],
    lossRate: 0.14,
    nameParts: ['Logistics', 'Freight', 'Shipping', 'Carriers', 'Transport'],
  },
  {
    name: 'Agri & Food Processing',
    weight: 2.4,
    industries: ['Sugar', 'Edible Oils', 'Seeds', 'Tea & Coffee', 'Poultry & Aquaculture'],
    volatility: 1.12,
    beta: [0.6, 1.0],
    pe: [8, 30],
    roe: [5, 20],
    revenueGrowth: [-4, 20],
    operatingMargin: [5, 15],
    netMargin: [2, 8],
    debtToEquity: [0.2, 1.5],
    dividendYield: [0.4, 3],
    lossRate: 0.14,
    nameParts: ['Agro', 'Sugars', 'Oils', 'Plantations', 'Agritech', 'Farms'],
  },
];

export const SECTOR_BY_NAME: ReadonlyMap<string, SectorProfile> = new Map(
  SECTORS.map(s => [s.name, s]),
);

/**
 * Lenders: operating margin is not reported. Debt/equity is reported for
 * NBFCs and housing financiers (high, by design) but not for banks — see
 * NO_LEVERAGE_INDUSTRIES.
 */
export const LENDER_INDUSTRIES: ReadonlySet<string> = new Set([
  'Private Banks',
  'Public Sector Banks',
  'Small Finance Banks',
  'NBFC',
  'Housing Finance',
  'Microfinance',
]);

/** Industries where debt/equity is not meaningful at all (deposits/float funded). */
export const NO_LEVERAGE_INDUSTRIES: ReadonlySet<string> = new Set([
  'Private Banks',
  'Public Sector Banks',
  'Small Finance Banks',
  'Life Insurance',
  'General Insurance',
]);

export const SECTOR_NAMES: readonly string[] = SECTORS.map(s => s.name);
