import type { FilterCategory, FilterControl, FilterDefinition, Unit } from '@/types/filters';

/**
 * The screener's filter catalogue: 53 criteria across four categories.
 * `field` points into the engine's field registry; `control` decides how the
 * panel renders the input and how a value compiles to a condition.
 */

const range = (
  min: number,
  max: number,
  step: number,
  scale: 'linear' | 'log' = 'linear',
): FilterControl => ({
  type: 'range',
  min,
  max,
  step,
  scale,
});

const def = (
  id: string,
  label: string,
  category: FilterCategory,
  field: string,
  unit: Unit,
  control: FilterControl,
  description: string,
  extra: Partial<Pick<FilterDefinition, 'short' | 'keywords'>> = {},
): FilterDefinition => ({ id, label, category, field, unit, control, description, ...extra });

const above = (label: string, value: string) => ({
  type: 'relation' as const,
  targets: [{ value, label }],
});

export const MACD_LABELS: Record<string, string> = {
  BULLISH_CROSS: 'Bullish crossover',
  BULLISH: 'Bullish',
  NEUTRAL: 'Neutral',
  BEARISH: 'Bearish',
  BEARISH_CROSS: 'Bearish crossover',
};

export const BB_ZONE_LABELS: Record<string, string> = {
  ABOVE_UPPER: 'Above upper band',
  NEAR_UPPER: 'Near upper band',
  UPPER_HALF: 'Upper half',
  LOWER_HALF: 'Lower half',
  NEAR_LOWER: 'Near lower band',
  BELOW_LOWER: 'Below lower band',
};

export const FILTER_DEFINITIONS: readonly FilterDefinition[] = [
  // ---- Fundamentals ------------------------------------------------------
  def(
    'marketCap',
    'Market Cap',
    'fundamentals',
    'marketCap',
    'cr',
    range(0, 2_000_000, 1, 'log'),
    'Total market value of equity at the live price, ₹ crore.',
    { short: 'MCap', keywords: ['size', 'mcap'] },
  ),
  def(
    'pe',
    'P/E Ratio',
    'fundamentals',
    'pe',
    'plain',
    range(0, 150, 0.5),
    'Price over trailing-twelve-month EPS. Loss-making companies have no P/E and never match.',
    { short: 'P/E', keywords: ['valuation', 'earnings'] },
  ),
  def(
    'pb',
    'P/B Ratio',
    'fundamentals',
    'pb',
    'plain',
    range(0, 40, 0.1),
    'Price over book value per share.',
    { short: 'P/B', keywords: ['valuation', 'book'] },
  ),
  def(
    'eps',
    'EPS (TTM)',
    'fundamentals',
    'eps',
    'inr',
    range(-100, 1000, 1),
    'Trailing-twelve-month earnings per share, ₹.',
    { short: 'EPS' },
  ),
  def(
    'roe',
    'ROE',
    'fundamentals',
    'roe',
    'pct',
    range(-30, 60, 0.5),
    'Return on equity: net profit over shareholders’ equity.',
    { keywords: ['return', 'profitability'] },
  ),
  def(
    'roce',
    'ROCE',
    'fundamentals',
    'roce',
    'pct',
    range(-30, 60, 0.5),
    'Return on capital employed: operating profit over equity plus debt.',
    { keywords: ['return', 'capital'] },
  ),
  def(
    'debtToEquity',
    'Debt / Equity',
    'fundamentals',
    'debtToEquity',
    'plain',
    range(0, 5, 0.05),
    'Total debt over shareholders’ equity. Not reported for banks and insurers.',
    { short: 'D/E', keywords: ['leverage', 'borrowing'] },
  ),
  def(
    'dividendYield',
    'Dividend Yield',
    'fundamentals',
    'dividendYield',
    'pct',
    range(0, 10, 0.1),
    'Trailing dividend per share over the live price.',
    { short: 'Div Yield', keywords: ['income', 'payout'] },
  ),
  def(
    'revenueGrowth',
    'Revenue Growth',
    'fundamentals',
    'revenueGrowth',
    'pct',
    range(-30, 60, 1),
    'Year-on-year growth in revenue.',
    { short: 'Rev Growth', keywords: ['sales', 'topline'] },
  ),
  def(
    'profitGrowth',
    'Profit Growth',
    'fundamentals',
    'profitGrowth',
    'pct',
    range(-100, 100, 1),
    'Year-on-year growth in net profit.',
    { short: 'Profit Growth', keywords: ['earnings', 'bottomline'] },
  ),
  def(
    'operatingMargin',
    'Operating Margin',
    'fundamentals',
    'operatingMargin',
    'pct',
    range(-20, 60, 0.5),
    'Operating profit over revenue. Not reported for lenders.',
    { short: 'OPM' },
  ),
  def(
    'netMargin',
    'Net Margin',
    'fundamentals',
    'netMargin',
    'pct',
    range(-30, 40, 0.5),
    'Net profit over revenue.',
    { short: 'NPM' },
  ),
  def(
    'pegRatio',
    'PEG Ratio',
    'fundamentals',
    'pegRatio',
    'plain',
    range(0, 5, 0.05),
    'P/E divided by profit growth. Undefined when growth is not positive.',
    { short: 'PEG' },
  ),
  def(
    'evToEbitda',
    'EV / EBITDA',
    'fundamentals',
    'evToEbitda',
    'x',
    range(0, 80, 0.5),
    'Enterprise value over EBITDA.',
    { short: 'EV/EBITDA' },
  ),
  def(
    'currentRatio',
    'Current Ratio',
    'fundamentals',
    'currentRatio',
    'x',
    range(0, 6, 0.05),
    'Current assets over current liabilities.',
    { keywords: ['liquidity'] },
  ),
  def(
    'interestCoverage',
    'Interest Coverage',
    'fundamentals',
    'interestCoverage',
    'x',
    range(0, 100, 0.5),
    'Operating profit over interest expense.',
    { short: 'Int. Cover' },
  ),
  def(
    'promoterHolding',
    'Promoter Holding',
    'fundamentals',
    'promoterHolding',
    'pct',
    range(0, 100, 1),
    'Share of equity held by the promoter group.',
    { short: 'Promoter', keywords: ['ownership', 'shareholding'] },
  ),
  def(
    'fiiHolding',
    'FII Holding',
    'fundamentals',
    'fiiHolding',
    'pct',
    range(0, 50, 0.5),
    'Share held by foreign institutional investors.',
    { short: 'FII', keywords: ['foreign', 'institutional'] },
  ),
  def(
    'diiHolding',
    'DII Holding',
    'fundamentals',
    'diiHolding',
    'pct',
    range(0, 40, 0.5),
    'Share held by domestic institutions (mutual funds, insurers).',
    { short: 'DII', keywords: ['mutual fund', 'institutional'] },
  ),
  def(
    'pledgedPercent',
    'Promoter Pledge',
    'fundamentals',
    'pledgedPercent',
    'pct',
    range(0, 60, 1),
    'Share of promoter holding pledged as collateral.',
    { short: 'Pledge' },
  ),
  def(
    'isProfitable',
    'Profitable (TTM)',
    'fundamentals',
    'isProfitable',
    'plain',
    { type: 'boolean' },
    'Positive trailing-twelve-month earnings.',
    { short: 'Profitable' },
  ),
  def(
    'paysDividend',
    'Pays Dividend',
    'fundamentals',
    'paysDividend',
    'plain',
    { type: 'boolean' },
    'Has paid a dividend in the trailing twelve months.',
    { short: 'Dividend' },
  ),
  def(
    'debtFree',
    'Debt Free',
    'fundamentals',
    'debtFree',
    'plain',
    { type: 'boolean' },
    'Debt/equity below 0.05.',
    { short: 'Debt Free' },
  ),

  // ---- Market data -------------------------------------------------------
  def(
    'price',
    'Price (LTP)',
    'market',
    'price',
    'inr',
    range(0, 50_000, 0.05, 'log'),
    'Last traded price, updated live.',
    { short: 'LTP', keywords: ['ltp', 'last'] },
  ),
  def(
    'changePercent',
    'Change %',
    'market',
    'changePercent',
    'pct',
    range(-20, 20, 0.1),
    'Change from the previous close, updated live.',
    { short: 'Chg %', keywords: ['gainers', 'losers'] },
  ),
  def(
    'volume',
    'Volume',
    'market',
    'volume',
    'shares',
    range(0, 50_000_000, 100, 'log'),
    'Shares traded today, updated live.',
    { keywords: ['traded'] },
  ),
  def(
    'avgVolume',
    'Average Volume (20D)',
    'market',
    'avgVolume',
    'shares',
    range(0, 50_000_000, 100, 'log'),
    'Average shares traded per session over the last 20 sessions.',
    { short: 'Avg Vol', keywords: ['liquidity'] },
  ),
  def(
    'turnover',
    'Turnover',
    'market',
    'turnover',
    'cr',
    range(0, 5_000, 0.01, 'log'),
    'Value traded today, ₹ crore.',
    { keywords: ['value traded', 'liquidity'] },
  ),
  def(
    'pctFrom52High',
    'Below 52W High',
    'market',
    'pctFrom52High',
    'pct',
    range(0, 90, 0.5),
    'How far the price sits below its 52-week high.',
    { short: 'From 52W High', keywords: ['52 week', 'high'] },
  ),
  def(
    'pctFrom52Low',
    'Above 52W Low',
    'market',
    'pctFrom52Low',
    'pct',
    range(0, 500, 1),
    'How far the price sits above its 52-week low.',
    { short: 'From 52W Low', keywords: ['52 week', 'low'] },
  ),
  def(
    'return1W',
    'Return 1W',
    'market',
    'return1W',
    'pct',
    range(-40, 60, 0.5),
    'Price return over five sessions.',
    { short: '1W' },
  ),
  def(
    'return1M',
    'Return 1M',
    'market',
    'return1M',
    'pct',
    range(-50, 100, 1),
    'Price return over one month.',
    { short: '1M' },
  ),
  def(
    'return3M',
    'Return 3M',
    'market',
    'return3M',
    'pct',
    range(-60, 150, 1),
    'Price return over three months.',
    { short: '3M' },
  ),
  def(
    'return1Y',
    'Return 1Y',
    'market',
    'return1Y',
    'pct',
    range(-80, 300, 1),
    'Price return over one year.',
    { short: '1Y' },
  ),
  def(
    'beta',
    'Beta',
    'market',
    'beta',
    'plain',
    range(-0.5, 2.5, 0.05),
    'Sensitivity to market moves, estimated over 252 sessions.',
    { keywords: ['risk', 'market'] },
  ),
  def(
    'volatility',
    'Volatility (60D)',
    'market',
    'volatility',
    'pct',
    range(0, 150, 1),
    'Annualised volatility of daily returns over 60 sessions.',
    { short: 'Volatility', keywords: ['risk'] },
  ),

  // ---- Classification ----------------------------------------------------
  def(
    'exchange',
    'Exchange',
    'classification',
    'exchange',
    'plain',
    { type: 'multiselect', source: 'exchange' },
    'Primary listing exchange.',
    { keywords: ['nse', 'bse'] },
  ),
  def(
    'sector',
    'Sector',
    'classification',
    'sector',
    'plain',
    { type: 'multiselect', source: 'sector' },
    'Macro-economic sector.',
  ),
  def(
    'industry',
    'Industry',
    'classification',
    'industry',
    'plain',
    { type: 'multiselect', source: 'industry' },
    'Industry within the sector.',
  ),
  def(
    'marketCapCategory',
    'Market Cap Class',
    'classification',
    'marketCapCategory',
    'plain',
    { type: 'multiselect', source: 'marketCapCategory' },
    'Large: top 100 by market cap · Mid: 101–250 · Small: 251–1,000 · Micro: the rest.',
    { short: 'Cap Class', keywords: ['large cap', 'mid cap', 'small cap'] },
  ),
  def(
    'indices',
    'Index Membership',
    'classification',
    'indices',
    'plain',
    { type: 'multiselect', source: 'indices' },
    'Member of any selected index.',
    { short: 'Index', keywords: ['nifty', 'sensex'] },
  ),

  // ---- Technical ---------------------------------------------------------
  def(
    'rsi14',
    'RSI (14)',
    'technical',
    'rsi14',
    'plain',
    range(0, 100, 1),
    'Wilder’s 14-session Relative Strength Index. Above 70 is commonly read as overbought, below 30 as oversold.',
    { short: 'RSI', keywords: ['momentum', 'overbought', 'oversold'] },
  ),
  def(
    'priceSma20',
    'Price vs SMA 20',
    'technical',
    'price',
    'plain',
    above('SMA 20', 'sma20'),
    'Live price above or below the 20-session simple moving average.',
    { short: 'Price/SMA20', keywords: ['moving average'] },
  ),
  def(
    'priceSma50',
    'Price vs SMA 50',
    'technical',
    'price',
    'plain',
    above('SMA 50', 'sma50'),
    'Live price above or below the 50-session simple moving average.',
    { short: 'Price/SMA50', keywords: ['moving average', 'trend'] },
  ),
  def(
    'priceSma200',
    'Price vs SMA 200',
    'technical',
    'price',
    'plain',
    above('SMA 200', 'sma200'),
    'Live price above or below the 200-session simple moving average.',
    { short: 'Price/SMA200', keywords: ['moving average', 'long term trend'] },
  ),
  def(
    'emaCross',
    'EMA 12 vs EMA 26',
    'technical',
    'ema12',
    'plain',
    above('EMA 26', 'ema26'),
    'Fast EMA above or below the slow EMA.',
    { short: 'EMA 12/26', keywords: ['crossover'] },
  ),
  def(
    'trendState',
    'SMA 50 vs SMA 200',
    'technical',
    'trendState',
    'plain',
    {
      type: 'select',
      options: [
        { value: 'GOLDEN', label: 'SMA 50 above SMA 200' },
        { value: 'DEATH', label: 'SMA 50 below SMA 200' },
      ],
    },
    'Golden cross regime (50 above 200) or death cross regime (50 below 200).',
    { short: 'SMA 50/200', keywords: ['golden cross', 'death cross'] },
  ),
  def(
    'macdState',
    'MACD (12, 26, 9)',
    'technical',
    'macdState',
    'plain',
    { type: 'multiselect', source: 'macdState', labels: MACD_LABELS },
    'MACD line relative to its signal line; crossovers happened in the latest session.',
    { short: 'MACD' },
  ),
  def(
    'bbPercentB',
    'Bollinger %B',
    'technical',
    'bbPercentB',
    'plain',
    range(-0.5, 1.5, 0.01),
    'Position within the 20-session, 2σ Bollinger Bands: 0 = lower band, 1 = upper band.',
    { short: '%B', keywords: ['bollinger', 'bands'] },
  ),
  def(
    'bbZone',
    'Bollinger Zone',
    'technical',
    'bbZone',
    'plain',
    { type: 'multiselect', source: 'bbZone', labels: BB_ZONE_LABELS },
    'Where the price sits relative to the Bollinger Bands.',
    { short: 'BB Zone', keywords: ['bollinger'] },
  ),
  def(
    'relativeVolume',
    'Volume vs Average',
    'technical',
    'relativeVolume',
    'x',
    range(0, 10, 0.1),
    'Today’s volume as a multiple of the 20-session average.',
    { short: 'Rel Vol', keywords: ['surge', 'spike'] },
  ),
  def(
    'atrPercent',
    'ATR %',
    'technical',
    'atrPercent',
    'pct',
    range(0, 15, 0.1),
    '14-session Average True Range as a share of price.',
    { short: 'ATR %', keywords: ['volatility', 'range'] },
  ),
  def(
    'priceVsSma200',
    'Distance from SMA 200',
    'technical',
    'priceVsSma200',
    'pct',
    range(-60, 100, 1),
    'How far the price is from its 200-session average, in percent.',
    { short: 'Δ SMA200' },
  ),
];

export const FILTER_BY_ID: ReadonlyMap<string, FilterDefinition> = new Map(
  FILTER_DEFINITIONS.map(d => [d.id, d]),
);

export const CATEGORY_ORDER: readonly FilterCategory[] = [
  'fundamentals',
  'market',
  'classification',
  'technical',
];

export const CATEGORY_LABELS: Record<FilterCategory, string> = {
  fundamentals: 'Fundamentals',
  market: 'Market Data',
  classification: 'Classification',
  technical: 'Technical',
};

export const FILTER_COUNT = FILTER_DEFINITIONS.length;
